version: '3.8'

services:
  prompting-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Map container port 8080 to host port 8080 (necessary for browser access)
    environment:
      - PYTHONUNBUFFERED=1
      - MARIMO_NO_ANALYTICS=1  # Disable usage analytics
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./data:/app/data  # For persistent data
      - ./prompting:/app/prompting  # To allow live changes to code during development
