name: Bump version and publish

on:
  workflow_dispatch:


jobs:
  tagging:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}

    steps:
      - name: Generate Tag
        id: tag
        uses: tschm/cradle/actions/tag@v0.1.56
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #build_package: 'false'

  docker:
    runs-on: ubuntu-latest
    needs: tagging
    steps:

      - name: "Build and publish the Container"
        uses: tschm/cradle/actions/docker@v0.1.56
        with:
          github_actor: ${{ github.actor }}
          github_repository: ${{ github.repository }}
          tag: ${{ needs.tagging.outputs.new_tag }}
          github_token: ${{ secrets.github_token }}
